
package Vista;

import Controlador.PinturaController.PinturaController;
import Controlador.TDA_Lista.ListaEnlazadaServices;
import Controlador.TDA_Lista.TipoOrdenacion;
import Modelo.DatosPinturas;
import Vista.Tablas.TablaPinturas;
import javax.swing.JOptionPane;

/**
 *
 * @author Hilary Madeley Calva Camacho
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    TablaPinturas tC = new TablaPinturas();
    PinturaController ctrlCuenta = new PinturaController();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarTabla();
        this.setTitle("SISTEMA DE ADMINISTRACION DE PINTURAS PARA CASAS");
        
    }
    
    private void cargarTabla() {
        tC.setListaPinturas(ctrlCuenta.guardarLista());
        tblCuenta.setModel(tC);
        tblCuenta.updateUI();
    }
    
    private void cargarTablaOrden(ListaEnlazadaServices<DatosPinturas> listaPrueba) {
        tC.setListaPinturas(listaPrueba);
        tblOrden.setModel(tC);
        tblOrden.updateUI();
    }
    
    private String cambiarNombre(){
        String nr = cbxAtributo.getSelectedItem().toString();
        if (nr.equals("Color") ) {
            nr = "color";
        }else{
            if (nr.equals("Marca")) {
                nr = "marcaPintura";
            } else{
                if (nr.equals("Precio")) {
                    nr = "precio";
                }else{
                    if (nr.equals("Tipo")) {
                        nr = "tipoP";
                    }
                }
            }
        }
        return nr;
    }
    
    private void ordenarShell(){
        
        if (cbxOrden.getSelectedIndex()==1) {
            JTxtTiempo.setText("");
            long inicio = System.currentTimeMillis();
            ctrlCuenta.ordenarShell(cambiarNombre(), TipoOrdenacion.ASCENDENTE);
            long fin = System.currentTimeMillis();
            cargarTablaOrden(ctrlCuenta.getListaPinturas());
            double tiempo = (double) ((fin-inicio)/1000);
            JTxtTiempo.setText("Tiempo estimado: \n" +String.valueOf(tiempo));
        } else{
            if (cbxOrden.getSelectedIndex()==2) {
                JTxtTiempo.setText("");
                long inicio = System.currentTimeMillis();
                ctrlCuenta.ordenarShell(cambiarNombre(), TipoOrdenacion.DESCENDENTE);
                long fin = System.currentTimeMillis();
                cargarTablaOrden(ctrlCuenta.getListaPinturas());
                double tiempo = (double) ((fin-inicio)/1000);
                JTxtTiempo.setText("Tiempo estimado: \n" +String.valueOf(tiempo));
            } else {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun orden");
            }
        }      
    }
    
    private void ordenarQuickShort(){
        if (cbxOrden.getSelectedIndex()==1) {
            JTxtTiempo.setText("");
            long inicio = System.currentTimeMillis();
            ctrlCuenta.ordenarQuickShort(cambiarNombre(), TipoOrdenacion.ASCENDENTE);
            long fin = System.currentTimeMillis();
            cargarTablaOrden(ctrlCuenta.getListaPinturas());
            double tiempo = (double) ((fin-inicio)/1000);
            JTxtTiempo.setText("Tiempo estimado: \n" +String.valueOf(tiempo));
        } else{
            if (cbxOrden.getSelectedIndex()==2) {
                JTxtTiempo.setText("");
                long inicio = System.currentTimeMillis();
                ctrlCuenta.ordenarQuickShort(cambiarNombre(), TipoOrdenacion.DESCENDENTE);
                long fin = System.currentTimeMillis();
                cargarTablaOrden(ctrlCuenta.getListaPinturas());
                double tiempo = (double) ((fin-inicio)/1000);
                JTxtTiempo.setText("Tiempo estimado: \n" +String.valueOf(tiempo));
            } else {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun orden");
            }
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxAtributo = new javax.swing.JComboBox<>();
        cbxMetodo = new javax.swing.JComboBox<>();
        cbxOrden = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrden = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTxtTiempo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Color", "Marca", "Precio", "Tipo" }));
        jPanel1.add(cbxAtributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 130, -1));

        cbxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Shell", "Quickshort" }));
        jPanel1.add(cbxMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 130, -1));

        cbxOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ascendente", "Descendente" }));
        jPanel1.add(cbxOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 130, -1));

        tblCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCuenta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 420, 630));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PINTURAS PARA CASAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 270, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Orden:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Método:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATOS ORDENADOS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ordenar por:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TIEMPO DE BUSQUEDA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 130, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SISTEMA DE ADMINISTRACION DE ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 390, 50));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SECCIÓN DE ORDENAMIENTO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 210, 30));

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        tblOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblOrden);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 300, 390));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(3, 3, 57));
        jLabel6.setText("DATOS PINTURAS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 290, 40));

        JTxtTiempo.setEditable(false);
        JTxtTiempo.setColumns(20);
        JTxtTiempo.setRows(5);
        jScrollPane2.setViewportView(JTxtTiempo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 140, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FONDO_AMI.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 530, 520));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FONDO_BL.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 770));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FONDO_AMI.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 530, 410));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FONDO_AMI.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        int seleccion = cbxMetodo.getSelectedIndex();
        switch (seleccion) {
            case 1:
                ordenarShell();
                break;
            case 2:
                ordenarQuickShort();
                break;
            default:
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun metodo");
        }      
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTxtTiempo;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JComboBox<String> cbxAtributo;
    private javax.swing.JComboBox<String> cbxMetodo;
    private javax.swing.JComboBox<String> cbxOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCuenta;
    private javax.swing.JTable tblOrden;
    // End of variables declaration//GEN-END:variables
}
